### ISSUE TITLE
httpx Library < 0.23 used by django-amplitude Contains Critical Vulnerability

### ISSUE THREAD

**Issue by colinbjohnson** [pyepye/django-amplitude#8]
The fixed version of the httpx dependency as defined in the "master" version of the `poetry.lock` (https://github.com/pyepye/django-amplitude/commit/c338ea5d87246c5c2022e4ef3942de4bc24b0b21) file contains a critical vulnerability that is described here: https://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-41945.

**Comment by pyepye** [comment]
Thanks @colinbjohnson - this is finally fixed.

**Comment by 9128305** [comment]
@pyepye Could you just remove upper constraints of dependencies?

**Comment by pyepye** [comment]
Thanks for the PR @9128305
